{{- if .Values.app.publish }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "_helpers.certificate.name" . }}
  namespace: {{ .Values.app.env }}
spec:
  commonName: {{ .Values.app.domain }}
  secretName: {{ include "_helpers.certificate.name" . }}
  dnsNames:
    - {{ .Values.app.domain }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
{{- end }}