{{- if .Values.app.publish }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "_helpers.ingress.name" . }}
  namespace: {{ .Values.app.env }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.app.domain }}`)
      kind: Rule
      services:
        - name: {{ include "_helpers.service.name" . }}
          port: 80
  tls:
    secretName: {{ include "_helpers.certificate.name" . }}
{{- end }}
